{
  "uid" : "9358666a7a130c4f",
  "name" : "test_failedTestCase",
  "fullName" : "test_EndToEndCash#test_failedTestCase",
  "historyId" : "f478bdd67a14490876c99b8cbdc0eb5e",
  "time" : {
    "start" : 1643863311522,
    "stop" : 1643863311522,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: This is a failed testcase\nassert False",
  "statusTrace" : "def test_failedTestCase():\n>       assert False,\"This is a failed testcase\"\nE       AssertionError: This is a failed testcase\nE       assert False\n\ntest_EndToEndCash.py:109: AssertionError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_EndToEndCash"
  }, {
    "name" : "host",
    "value" : "ezetap"
  }, {
    "name" : "thread",
    "value" : "34668-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_EndToEndCash"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Failed Testcases",
      "matchedStatuses" : [ "failed" ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "9358666a7a130c4f.json",
  "parameterValues" : [ ]
}